const dictionary = {
    "fam": "family",
    "lit": "amazing",
    "fire": "amazing",
    "cringe": "awkward",
    "slay": "do amazing",
    "big yikes": "embarrassing",
    "no cap": "no lie",
    "sus": "suspicious",
    "simp": "overly attentive",
    "bet": "sure",
    "yeet": "throw",
    "gucci": "good",
    "mood": "feeling",
    "spill the tea": "gossip",
    "salty": "bitter",
    "ghosted": "ignored",
    "snatched": "looking good",
    "wig": "mind-blown",
    "high key": "obvious",
    "low key": "subtle",
    "AF": "very",
    "lit AF": "very amazing",
    "cray": "crazy",
    "GOAT": "greatest of all time",
    "on fleek": "perfect",
    "clap back": "retaliate",
    "extra": "over the top",
    "stan": "super fan",
    "shook": "shocked",
    "fire": "awesome",
    "ship": "support a relationship",
    "basic": "unoriginal",
    "Karen": "entitled woman",
    "big mood": "relatable",
    "flex": "show off",
    "hype": "excited",
    "savage": "bold",
    "shade": "insult",
    "thirsty": "attention-seeking",
    "vibe": "atmosphere",
    "yikes": "awkward",
    "woke": "socially aware",
    "adulting": "acting responsibly",
    "bop": "good song",
    "clout": "influence",
    "drag": "criticize",
    "finesse": "skillfully done",
    "grind": "work hard",
    "squad": "friends group",
    "stan": "fanatic fan",
    "triggered": "emotionally affected",
    "viral": "widely known",
    "bounce": "leave",
    "chill": "relax",
    "dope": "cool",
    "fire": "excellent",
    "legit": "real",
    "pop off": "go well",
    "real talk": "serious discussion",
    "sick": "awesome",
    "tight": "close",
    "whip": "car",
    "extra": "too much",
    "cringe": "awkward",
    "lit": "great",
    "period": "end of discussion",
    "drag": "insult",
    "hype": "enthusiasm",
    "fam": "family",
    "big mood": "very relatable",
    "salty": "angry",
    "shook": "very surprised",
    "snatched": "fashionable",
    "wig": "amazed",
    "sus": "suspicious",
    "fire": "cool",
    "adulting": "being responsible",
    "bounce": "leave quickly",
    "clap back": "respond boldly",
    "flex": "brag",
    "slay": "succeed",
    "savage": "bold and unapologetic"
};
document.getElementById('translator-form').addEventListener('submit', (e) => {
    e.preventDefault(); // Prevenir recarga
    const inputText = document.getElementById('input-text').value.toLowerCase().trim(); // Texto de entrada
    const words = inputText.split(/\s+/); // Dividir en palabras
    const translatedWords = words.map(word => dictionary[word] || word); // Intentar traducir palabra por palabra
    const translatedText = translatedWords.join(' '); // Unir palabras traducidas

    // Mostrar resultado
    if (translatedText === inputText) {
        document.getElementById('output-text').value = "Error: Unable to translate.";
    } else {
        document.getElementById('output-text').value = translatedText;
    }
});
